### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Okta16** [CBHue/PyFuscation#7]
There is a specific version of Python 3.x where this script needs to run under? There is a sort of 'requirements.txt' with all dependancies required by the script?
 ←[91m[!] Obfuscating: powershell.ps1←[00m
Traceback (most recent call last):
  File "PyFuscation.py", line 297, in <module>
    main()
  File "PyFuscation.py", line 228, in main
    removeJunk(oFile)
  File "PyFuscation.py", line 43, in removeJunk
    realTimeMuxER(cmd)
  File "PyFuscation.py", line 31, in realTimeMuxER
    p = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Using it under Python 3.7 on a Windows 10 x64 machine.

**Comment by superswan** [comment]
See this issue 
#5 

The script heavily relies on sed for the text replacements. I've tried installing a sed binary for Windows, the script runs without errors but does not give the expected result (an obfuscated PS script). Tested with WSL and it runs fine so that may be an option.
